version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8888:8888"
    networks:
      - network
    volumes:
      - ./uploads:/go/src/app/uploads

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network

networks:
  network:
    driver: bridge
